dist: jammy
sudo: false
language: cpp

before_install:
  - pip install --user cpp-coveralls
install:
  - sudo apt-get install -y lcov
script:
  - cmake -H. -Bbuild
  - cmake --build build --config Debug --target coverage -j2
after_success:
  - coveralls --root . -E ".*gtest.*" -E ".*CMakeFiles.*" -E ".*_deps.*" -E ".*tests.*"
