name: Documentation

on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master, dev ]

jobs:
  docs:
    name: Build Doxygen and upload artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen
      - name: Configure (CMake)
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
      - name: Build docs target
        run: cmake --build build --target docs -j 2
      - name: Upload Doxygen HTML artifact
        uses: actions/upload-artifact@v4
        with:
          name: doxygen-html
          path: |
            docs/html/**
          if-no-files-found: error
          retention-days: 14
