name: Windows CI Test

on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master, dev ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure (CMake)
        shell: pwsh
        run: |
          cmake -S . -B build -A x64 -DLIB_ENABLE_TESTING=ON
      - name: Build
        shell: pwsh
        run: |
          cmake --build build --config Debug -- /m
      - name: Test
        shell: pwsh
        run: |
          ctest --test-dir build -C Debug --output-on-failure -j 2
